version: '3.3'
services:
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    # image: thimico/eureka
    container_name: eureka
    ports:
      - 8761:8761
    environment:
      EUREKA_PORT: 8761
      EUREKA_HOSTNAME: localhost