spring:
  profiles:
    active: '@app.profile.name@'
  application:
    name: '@project.artifactId@'

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
    prefer-ip-address: true
  client:
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka
    register-with-eureka: false
    fetch-registry: false

server:
  port: ${EUREKA_PORT:8761}